services:
  - type: web
    name: tennis-elo-api
    runtime: python
    region: virginia
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.api:app --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: KAGGLE_USERNAME
        sync: false
      - key: KAGGLE_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
